apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
  labels:
    app: django
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
      version: blue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: django
        version: blue
    spec:
      containers:
      - name: django-blue
        image: your-dockerhub-username/django-messaging:2.0   # <-- UPDATED VERSION
        ports:
        - containerPort: 8000
