pipeline {
    agent any
    environment {
        VENV = '.venv'
        PYTHON = 'python3'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/Wege0921/alx-backend-python.git',
                    branch: 'main'
            }
        }

        stage('Set up Python env') {
            steps {
                sh '''
                    set -eux
                    ${PYTHON} --version
                    ${PYTHON} -m venv ${VENV}
                    . ${VENV}/bin/activate
                    python -m pip install --upgrade pip
                    if [ -f messaging_app/requirements.txt ]; then
                      pip install -r messaging_app/requirements.txt
                    fi
                    pip install pytest pytest-html
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    set -eux
                    . ${VENV}/bin/activate
                    pytest -q --junitxml=pytest-report.xml --html=pytest-report.html --self-contained-html
                '''
            }
            post {
                always {
                    junit testResults: 'pytest-report.xml', allowEmptyResults: true
                    archiveArtifacts artifacts: 'pytest-report.xml, pytest-report.html', allowEmptyArchive: true, fingerprint: true
                }
            }
        }
    }
}
